### ISSUE TITLE
Uncaught TypeError: editor.getCommentStrings is not a function

### ISSUE THREAD

**Issue by wgor** [t9md/atom-hydrogen-helpers#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: HEAVYUSER
**Thrown From**: [hydrogen-helpers](https://github.com/t9md/atom-hydrogen-helpers) package 0.1.1

### Stack Trace

Uncaught TypeError: editor.getCommentStrings is not a function

```
At C:\Users\W\.atom\packages\hydrogen-helpers\lib\main.js:34

TypeError: editor.getCommentStrings is not a function
    at getCommentStartStrings (/packages/hydrogen-helpers/lib/main.js:34:17)
    at clearAllLineCells (/packages/hydrogen-helpers/lib/main.js:60:45)
    at HTMLElement.hydrogenHelperClearAllLineCells (/packages/hydrogen-helpers/lib/main.js:87:9)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.28.0/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.28.0/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
  2x -2:23.6.0 core:save (input.hidden-input)
  3x -2:17.6.0 hydrogen:run-and-move-down (input.hidden-input)
     -1:28.1.0 intentions:highlight (input.hidden-input)
     -1:27.6.0 core:copy (input.hidden-input)
     -1:23.3.0 intentions:highlight (input.hidden-input)
     -1:22.9.0 core:paste (input.hidden-input)
  8x -1:21.4.0 core:backspace (input.hidden-input)
 31x -0:44.6.0 core:move-right (input.hidden-input)
     -0:36.9.0 intentions:highlight (input.hidden-input)
     -0:36.5.0 core:save (input.hidden-input)
     -0:33 intentions:highlight (input.hidden-input)
     -0:32.6.0 editor:fold-at-indent-level-1 (input.hidden-input)
  2x -0:31 intentions:highlight (input.hidden-input)
     -0:27.1.0 editor:fold-at-indent-level-1 (input.hidden-input)
     -0:21.6.0 intentions:highlight (input.hidden-input)
     -0:20.4.0 hydrogen-helper:clear-all-line-cells (input.hidden-input)
```

### Non-Core Packages

```
atom-django 0.3.2 
atom-python-run 0.9.6 
atom-python-virtualenv 1.0.2 
autocomplete-python 1.10.5 
autocomplete-python-jedi 1.10.3-0 
browser-plus 0.0.98 
busy-signal 1.4.3 
close-tags 0.6.0 
comment 0.6.1 
django-templates 0.5.0 
file-icons 2.1.21 
highlight-selected 0.13.1 
html-nested-comments 3.4.0 
Hydrogen 2.5.1 
hydrogen-helpers 0.1.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
monokai 0.24.0 
package-cop 0.2.10 
platformio-ide-terminal 2.8.3 
predawn-syntax 1.0.4 
python-autopep8 0.1.3 
python-tools 0.6.9 
script 3.18.1 
```

**Comment by t9md** [comment]
Hi, sorry for this inconvenience, I no longer use/maintain this package, so I should have unpublished it.
Now I unpublished it.
